Repository OPM/opm-simulators, pull requests merged in 2025-06, with the labels that each got.

#6312 adjust to upstream API change
  opm/simulators/flow/ActionHandler.cpp
Labels: manual:irrelevant

#6280 Further updates and fixes to general controller
  opm/simulators/flow/NonlinearSolver.hpp
  opm/simulators/timestepping/AdaptiveTimeStepping.cpp
  opm/simulators/timestepping/AdaptiveTimeStepping.hpp
  opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
  opm/simulators/timestepping/SimulatorReport.cpp
  opm/simulators/timestepping/SimulatorReport.hpp
  opm/simulators/timestepping/TimeStepControl.cpp
  opm/simulators/timestepping/TimeStepControl.hpp
  opm/simulators/timestepping/TimeStepControlInterface.hpp
Labels: manual:new-feature

#6324 Update PRT reports
  opm/simulators/flow/LogOutputHelper.cpp
  tests/test_LogOutputHelper.cpp
Labels: manual:irrelevant

#6322 reusing primary variable indices and flags defined
  opm/simulators/wells/MultisegmentWellAssemble.hpp
Labels: manual:irrelevant

#6328 using PrimaryVariables::numWellEq in MultisegmentWellSegments
  opm/simulators/wells/MultisegmentWellSegments.cpp
Labels: manual:irrelevant

#6317 Also check operability for wells without thp control
  opm/simulators/wells/MultisegmentWell_impl.hpp
  opm/simulators/wells/StandardWell_impl.hpp
  opm/simulators/wells/WellInterface.hpp
  opm/simulators/wells/WellInterface_impl.hpp
Labels: manual:bugfix

#6333 using group_limit_action.oil instead of allRates for better code readability and potentially better flexibility
  opm/simulators/wells/BlackoilWellModelConstraints.cpp
Labels: manual:irrelevant

#6335 Fixing --enable-dry-run=1
  opm/models/blackoil/blackoilintensivequantities.hh
Labels: manual:irrelevant

#6329 Add CSV output of FIP and RESV data
  opm/simulators/flow/EclWriter.hpp
  opm/simulators/flow/LogOutputHelper.cpp
  opm/simulators/flow/LogOutputHelper.hpp
  opm/simulators/flow/OutputBlackoilModule.hpp
Labels: manual:enhancement

#6170 Reservoir coupling: Communicate group potentials from slaves and compute guide rates
  CMakeLists_files.cmake
  opm/models/utils/simulator.hh
  opm/simulators/flow/ReservoirCoupling.cpp
  opm/simulators/flow/ReservoirCoupling.hpp
  opm/simulators/flow/ReservoirCouplingMaster.cpp
  opm/simulators/flow/ReservoirCouplingMaster.hpp
  opm/simulators/flow/ReservoirCouplingMpiTraits.hpp
  opm/simulators/flow/ReservoirCouplingSlave.cpp
  opm/simulators/flow/ReservoirCouplingSlave.hpp
  opm/simulators/flow/ReservoirCouplingSpawnSlaves.cpp
  opm/simulators/flow/ReservoirCouplingSpawnSlaves.hpp
  opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
  opm/simulators/timestepping/AdaptiveTimeStepping.hpp
  opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
  opm/simulators/wells/BlackoilWellModel.hpp
  opm/simulators/wells/BlackoilWellModelGeneric.hpp
  opm/simulators/wells/BlackoilWellModelGuideRates.cpp
  opm/simulators/wells/BlackoilWellModelGuideRates.hpp
  opm/simulators/wells/BlackoilWellModel_impl.hpp
  opm/simulators/wells/GroupState.cpp
  opm/simulators/wells/GroupState.hpp
  opm/simulators/wells/GuideRateHandler.cpp
  opm/simulators/wells/GuideRateHandler.hpp
  opm/simulators/wells/WellGroupHelpers.cpp
Labels: manual:irrelevant

#6342 Fixed brace locations when compiling without CUDA
  opm/simulators/linalg/FlexibleSolver_impl.hpp
Labels: manual:irrelevant

#6343 Add include to get fmt::join.
  opm/simulators/wells/GuideRateHandler.cpp
Labels: manual:irrelevant

#6332 [BUG] TSMINZ instead of TSFMIN
  opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
Labels: manual:bugfix

#6351 tpfalinearizer: Add conditional storage for energy, diffusion and dispersion
  opm/models/blackoil/blackoillocalresidualtpfa.hh
  opm/models/discretization/common/tpfalinearizer.hh
Labels: manual:enhancement

#6352 Remove unneeded setPc() call.
  opm/simulators/flow/FlowProblemBlackoil.hpp
Labels: manual:irrelevant

#6330 (Partial) Support for parallel runs with CpGrid with LGRs
  compareECLFiles.cmake
  opm/simulators/flow/CollectDataOnIORank_impl.hpp
  opm/simulators/flow/CpGridVanguard.hpp
  opm/simulators/flow/GenericCpGridVanguard.cpp
  opm/simulators/flow/GenericCpGridVanguard.hpp
  opm/simulators/flow/OutputBlackoilModule.hpp
  opm/simulators/utils/ParallelEclipseState.hpp
Labels: manual:irrelevant

#6354 [cleanup] Remove unused setupCartesianToCompressed_()
  opm/simulators/flow/FlowBaseVanguard.hpp
Labels: manual:irrelevant

#6346 Add mobility thresholding to NLDD
  opm/simulators/flow/BlackoilModelNldd.hpp
  opm/simulators/flow/BlackoilModelParameters.cpp
  opm/simulators/flow/BlackoilModelParameters.hpp
  opm/simulators/flow/BlackoilModel_impl.hpp
  opm/simulators/timestepping/SimulatorReport.cpp
  opm/simulators/timestepping/SimulatorReport.hpp
Labels: manual:new-feature

#6359 Use if constexpr to handle conditionally stored members.
  flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp
  opm/models/blackoil/blackoilintensivequantities.hh
  opm/models/discretization/ecfv/ecfvstencil.hh
  opm/simulators/flow/EquilInitializer.hpp
  opm/simulators/flow/FlowProblemBlackoil.hpp
  opm/simulators/flow/OutputBlackoilModule.hpp
Labels: manual:irrelevant
