Repository OPM/opm-simulators, pull requests merged in 2025-10, with the labels that each got.

#6510 Add no-hysteresis variant of Flow
  CMakeLists.txt
  examples/problems/co2ptflashproblem.hh
  examples/problems/cuvetteproblem.hh
  examples/problems/infiltrationproblem.hh
  examples/problems/reservoirproblem.hh
  flow/flow_blackoil_nohyst.cpp
  flow/flow_blackoil_nohyst.hpp
  flow/flow_blackoil_nohyst_main.cpp
  opm/simulators/flow/FlowBaseProblemProperties.hpp
  opm/simulators/flow/FlowProblemBlackoilProperties.hpp
  opm/simulators/flow/FlowProblemCompProperties.hpp
  opm/simulators/flow/MainDispatchDynamic.cpp
  opm/simulators/flow/equil/EquilibrationHelpers.cpp
  opm/simulators/flow/equil/InitStateEquil.cpp
Labels: manual:enhancement

#6514 Janitoring: fix some doxy issues
  opm/simulators/flow/Transmissibility.hpp
  opm/simulators/flow/equil/EquilibrationHelpers.hpp
  opm/simulators/linalg/gpuistl/GpuSparseMatrixWrapper.hpp
Labels: manual:irrelevant

#6424 Hybrid newton flag
  CMakeLists_files.cmake
  opm/models/blackoil/blackoilenergymodules.hh
  opm/simulators/flow/FlowProblem.hpp
  opm/simulators/flow/FlowProblemBlackoil.hpp
  opm/simulators/flow/FlowProblemParameters.cpp
  opm/simulators/flow/FlowProblemParameters.hpp
  opm/simulators/flow/HybridNewton.hpp
  opm/simulators/flow/HybridNewtonConfig.hpp
  opm/simulators/linalg/PropertyTree.cpp
  opm/simulators/linalg/PropertyTree.hpp
  python/test/ml/README.md
  python/test/ml/__init__.py
  python/test/ml/hybrid_newton/README.md
  python/test/ml/hybrid_newton/__init__.py
  python/test/ml/hybrid_newton/test_hybrid_newton.py
  python/test/ml/hybrid_newton/utils.py
  python/test_data/SPE1CASE1b/SPE1CASE1.DATA
Labels: manual:new-feature

#6518 Generalize initial value retrieval of reduction operators
  opm/simulators/linalg/ParallelIstlInformation.cpp
  opm/simulators/linalg/ParallelIstlInformation.hpp
Labels: manual:irrelevant
