Repository OPM/opm-simulators, pull requests merged in 2025-07, with the labels that each got.

#6364 moving FluidSystem::waterEnabled runtime_error to CompWellInterface
  flowexperimental/comp/wells/CompWellInterface_impl.hpp
  flowexperimental/comp/wells/CompWellModel_impl.hpp
Labels: manual:irrelevant

#6365 Allow calling BlackoilIntensiveQuantities::update() without an ElementContext
  flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp
  opm/models/blackoil/blackoilbrinemodules.hh
  opm/models/blackoil/blackoildiffusionmodule.hh
  opm/models/blackoil/blackoilenergymodules.hh
  opm/models/blackoil/blackoilextbomodules.hh
  opm/models/blackoil/blackoilintensivequantities.hh
  opm/models/blackoil/blackoilsolventmodules.hh
  opm/simulators/aquifers/AquiferAnalytical.hpp
  opm/simulators/wells/StandardWell.hpp
  opm/simulators/wells/StandardWell_impl.hpp
Labels: manual:enhancement

#6370 Relax Upper Bound Check for Mobile Displacing Oil
  opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.cpp
  opm/simulators/utils/satfunc/ThreePointHorizontalConsistencyChecks.hpp
  tests/test_SatfuncConsistencyCheckManager.cpp
  tests/test_ThreePointHorizontalSatfuncConsistencyChecks.cpp
Labels: manual:irrelevant

#6369 Remove the if that discoordinates values on different ranks
  opm/simulators/wells/WellGroupHelpers.cpp
Labels: bug, manual:irrelevant

#6320 Cleaned up and fixed verbosity for time step controllers
  opm/simulators/timestepping/AdaptiveTimeStepping.cpp
  opm/simulators/timestepping/TimeStepControl.cpp
  opm/simulators/timestepping/TimeStepControl.hpp
Labels: manual:enhancement

#6339 rocsparseCPR update incl bug fixes
  opm/simulators/linalg/gpubridge/CprCreation.cpp
  opm/simulators/linalg/gpubridge/CprCreation.hpp
  opm/simulators/linalg/gpubridge/GpuBridge.cpp
  opm/simulators/linalg/gpubridge/Misc.hpp
  opm/simulators/linalg/gpubridge/MultisegmentWellContribution.cpp
  opm/simulators/linalg/gpubridge/Preconditioner.hpp
  opm/simulators/linalg/gpubridge/opencl/openclBILU0.cpp
  opm/simulators/linalg/gpubridge/opencl/openclBILU0.hpp
  opm/simulators/linalg/gpubridge/opencl/openclBISAI.cpp
  opm/simulators/linalg/gpubridge/opencl/openclBISAI.hpp
  opm/simulators/linalg/gpubridge/opencl/openclCPR.cpp
  opm/simulators/linalg/gpubridge/opencl/openclCPR.hpp
  opm/simulators/linalg/gpubridge/opencl/openclPreconditioner.hpp
  opm/simulators/linalg/gpubridge/opencl/openclSolverBackend.cpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseBILU0.cpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseBILU0.hpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseCPR.cpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseCPR.hpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseMatrix.cpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseMatrix.hpp
  opm/simulators/linalg/gpubridge/rocm/rocsparsePreconditioner.cpp
  opm/simulators/linalg/gpubridge/rocm/rocsparsePreconditioner.hpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseSolverBackend.cpp
  opm/simulators/linalg/gpubridge/rocm/rocsparseSolverBackend.hpp
Labels: manual:bugfix
