Repository OPM/opm-simulators, pull requests merged in 2025-05, with the labels that each got.

#6235 Reduce discontinuities in serial simulation for CpGrid with LGRs
  opm/models/utils/simulator.hh
  opm/simulators/flow/CpGridVanguard.hpp
  opm/simulators/flow/FlowBaseVanguard.hpp
Labels: manual:irrelevant

#6248 Correct warning
  opm/simulators/flow/CpGridVanguard.hpp
Labels: manual:irrelevant

#6246 Throw if bhp is NaN in findTHP
  opm/simulators/wells/MultisegmentWell_impl.hpp
  opm/simulators/wells/VFPHelpers.cpp
Labels: manual:irrelevant

#6244 Move throws inside the loop over all wells to after the end of the loop
  opm/simulators/wells/WellState.cpp
Labels: manual:irrelevant

#6238 Assign Shut Connection Data for Owned Wells Only
  opm/simulators/flow/GenericOutputBlackoilModule.cpp
  opm/simulators/flow/GenericOutputBlackoilModule.hpp
  opm/simulators/flow/OutputBlackoilModule.hpp
  opm/simulators/flow/OutputCompositionalModule.hpp
  opm/simulators/flow/RFTContainer.cpp
  opm/simulators/wells/BlackoilWellModel.hpp
  opm/simulators/wells/BlackoilWellModelGeneric.cpp
  opm/simulators/wells/BlackoilWellModelGeneric.hpp
Labels: manual:irrelevant

#6254 fixed: pass by pointer instead of reference
  opm/simulators/linalg/ISTLSolver.cpp
  opm/simulators/linalg/ISTLSolver.hpp
Labels: manual:irrelevant

#6258 fixing compilation with older gcc compiler (GCC 9.X)
  opm/simulators/timestepping/AdaptiveTimeStepping.hpp
Labels: manual:irrelevant

#6260 FvBaseAdLocalLinearizer: some janitoring
  opm/models/discretization/common/baseauxiliarymodule.hh
  opm/models/discretization/common/fvbaseadlocallinearizer.hh
Labels: manual:irrelevant

#6247 Prefer In-Place Construction of Data::Connection Objects
  opm/simulators/flow/RFTContainer.cpp
Labels: manual:irrelevant

#6256 remove python 3.6 and 3.7 packages
  python/generate-pypi-package.sh
Labels: manual:irrelevant

#6262 FvBase(BoundaryContext|Constraints): some janitoring
  opm/models/discretization/common/fvbaseboundarycontext.hh
  opm/models/discretization/common/fvbaseconstraints.hh
  opm/models/discretization/common/fvbaseconstraintscontext.hh
Labels: manual:irrelevant

#6218 DiffusionModule: some janitoring
  opm/models/common/diffusionmodule.hh
Labels: manual:irrelevant

#6219 DirectionalMobility: janitoring
  flowexperimental/BlackOilIntensiveQuantitiesGlobalIndex.hpp
  opm/models/blackoil/blackoilintensivequantities.hh
  opm/models/common/directionalmobility.hh
  opm/models/common/multiphasebaseproblem.hh
  opm/simulators/flow/FlowProblem.hpp
Labels: manual:irrelevant

#6263 FvBaseDiscretization(FemAdapt): Some janitoring
  opm/models/blackoil/blackoilenergymodules.hh
  opm/models/blackoil/blackoilmicpmodules.hh
  opm/models/blackoil/blackoilmodel.hh
  opm/models/blackoil/blackoilpolymermodules.hh
  opm/models/blackoil/blackoilsolventmodules.hh
  opm/models/common/multiphasebasemodel.hh
  opm/models/discretefracture/discretefracturemodel.hh
  opm/models/discretization/common/fvbasediscretization.hh
  opm/models/discretization/common/fvbasediscretizationfemadapt.hh
  opm/models/flash/flashmodel.hh
  opm/models/immiscible/immisciblemodel.hh
  opm/models/ncp/ncpmodel.hh
  opm/models/ptflash/flashmodel.hh
  opm/models/pvs/pvsmodel.hh
  opm/simulators/flow/FlowProblemBlackoil.hpp
Labels: manual:irrelevant

#6206 Make TracerModel thread parallel
  opm/simulators/flow/TracerModel.hpp
Labels: manual:enhancement

#6241 Instatiate preconditioners directly with GPU matrices
  CMakeLists_files.cmake
  opm/simulators/linalg/StandardPreconditioners_gpu_serial.hpp
  opm/simulators/linalg/StandardPreconditioners_mpi.hpp
  opm/simulators/linalg/StandardPreconditioners_serial.hpp
  opm/simulators/linalg/gpuistl/GpuDILU.cpp
  opm/simulators/linalg/gpuistl/GpuDILU.hpp
  opm/simulators/linalg/gpuistl/GpuJac.cpp
  opm/simulators/linalg/gpuistl/GpuJac.hpp
  opm/simulators/linalg/gpuistl/GpuSeqILU0.cpp
  opm/simulators/linalg/gpuistl/GpuSeqILU0.hpp
  opm/simulators/linalg/gpuistl/GpuSparseMatrix.cpp
  opm/simulators/linalg/gpuistl/GpuSparseMatrix.hpp
  opm/simulators/linalg/gpuistl/GpuVector.cpp
  opm/simulators/linalg/gpuistl/GpuVector.hpp
  opm/simulators/linalg/gpuistl/OpmGpuILU0.cpp
  opm/simulators/linalg/gpuistl/OpmGpuILU0.hpp
  opm/simulators/linalg/gpuistl/PreconditionerCPUMatrixToGPUMatrix.hpp
  opm/simulators/linalg/gpuistl/detail/CuSparseResource.hpp
  opm/simulators/linalg/gpuistl/detail/CuSparseResource_impl.hpp
  opm/simulators/linalg/gpuistl/detail/gpusparse_matrix_operations.cu
  opm/simulators/linalg/gpuistl/detail/gpusparse_matrix_operations.hpp
  opm/simulators/linalg/gpuistl/detail/preconditionerKernels/JacKernels.cu
  opm/simulators/linalg/gpuistl/detail/preconditionerKernels/JacKernels.hpp
  opm/simulators/linalg/is_gpu_operator.hpp
  tests/gpuistl/test_GpuDILU.cpp
  tests/gpuistl/test_GpuJac.cpp
  tests/gpuistl/test_preconditioner_factory_gpu.cpp
Labels: manual:enhancement

#6271 FvBaseElementContext: some janitoring
  opm/models/discretization/common/fvbaseelementcontext.hh
Labels: manual:irrelevant

#6009 Time step rejection if tolerance test fails
  opm/simulators/flow/NonlinearSolver.hpp
  opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
  opm/simulators/timestepping/AdaptiveTimeStepping.cpp
  opm/simulators/timestepping/AdaptiveTimeStepping.hpp
  opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
  opm/simulators/timestepping/TimeStepControl.cpp
  opm/simulators/timestepping/TimeStepControl.hpp
  opm/simulators/timestepping/TimeStepControlInterface.hpp
Labels: manual:new-feature

#6272 unifying instantiation of variants related to Indices
  CMakeLists_files.cmake
  opm/simulators/utils/ComponentName.cpp
  opm/simulators/utils/InstantiationIndicesMacros.hpp
  opm/simulators/wells/MultisegmentWellAssemble.cpp
  opm/simulators/wells/MultisegmentWellEval.cpp
  opm/simulators/wells/MultisegmentWellPrimaryVariables.cpp
  opm/simulators/wells/MultisegmentWellSegments.cpp
  opm/simulators/wells/StandardWellAssemble.cpp
  opm/simulators/wells/StandardWellConnections.cpp
  opm/simulators/wells/StandardWellEval.cpp
  opm/simulators/wells/StandardWellPrimaryVariables.cpp
  opm/simulators/wells/WellInterfaceIndices.cpp
Labels: manual:irrelevant

#6274 FvBase(ExtensiveQuantites|FdLocalLinearizer): some janitoring
  opm/models/discretization/common/fvbaseextensivequantities.hh
  opm/models/discretization/common/fvbasefdlocallinearizer.hh
Labels: manual:irrelevant

#6261 Run Saturation Function Consistency Check on Main Grid Only
  opm/simulators/flow/FlowProblemBlackoil.hpp
Labels: manual:irrelevant

#6276 FvBase(IntensiveQuantities|GradientCalculator): some janitoring
  opm/models/discretization/common/fvbasegradientcalculator.hh
  opm/models/discretization/common/fvbaseintensivequantities.hh
Labels: manual:irrelevant

#6252 Enable New Saturation Function Consistency Checks by Default
  opm/simulators/flow/FlowProblemParameters.hpp
Labels: manual:new-feature

#6281 FvBase(LocalResidual|NewtonConvergenceWriter|NewtonMethod|PrimaryVariables): some janitoring
  opm/models/discretization/common/fvbaselocalresidual.hh
  opm/models/discretization/common/fvbasenewtonconvergencewriter.hh
  opm/models/discretization/common/fvbasenewtonmethod.hh
  opm/models/discretization/common/fvbaseprimaryvariables.hh
Labels: manual:irrelevant

#6265 Add Regression Tests for UDA Compatibility
  parallelTests.cmake
  regressionTests.cmake
Labels: manual:irrelevant

#6282 FvBaseProblem: some janitoring
  opm/models/discretization/common/fvbaseproblem.hh
Labels: manual:irrelevant

#6283 TpfaLinearizer: some janitoring
  opm/models/discretization/common/linearizationtype.hh
  opm/models/discretization/common/restrictprolong.hh
  opm/models/discretization/common/tpfalinearizer.hh
Labels: manual:irrelevant

#6284 ECFV classes: some janitoring
  opm/models/discretization/ecfv/ecfvbaseoutputmodule.hh
  opm/models/discretization/ecfv/ecfvdiscretization.hh
  opm/models/discretization/ecfv/ecfvgridcommhandlefactory.hh
  opm/models/discretization/ecfv/ecfvstencil.hh
Labels: manual:irrelevant

#6286 BlackoilModel: some janitoring
  opm/models/blackoil/blackoilboundaryratevector.hh
  opm/models/blackoil/blackoilbrinemodules.hh
  opm/models/blackoil/blackoilconvectivemixingmodule.hh
  opm/models/blackoil/blackoildarcyfluxmodule.hh
  opm/models/blackoil/blackoildiffusionmodule.hh
  opm/models/blackoil/blackoildispersionmodule.hh
  opm/models/blackoil/blackoilenergymodules.hh
  opm/models/blackoil/blackoilextbomodules.hh
  opm/models/blackoil/blackoilfoammodules.hh
Labels: manual:irrelevant

#6288 BlackOilModel: janitoring part2
  opm/models/blackoil/blackoilintensivequantities.hh
  opm/models/blackoil/blackoillocalresidual.hh
  opm/models/blackoil/blackoillocalresidualtpfa.hh
  opm/models/blackoil/blackoilmicpmodules.hh
  opm/models/blackoil/blackoilmodel.hh
  opm/models/blackoil/blackoilnewtonmethod.hpp
  opm/models/blackoil/blackoilpolymermodules.hh
  opm/models/blackoil/blackoilprimaryvariables.hh
  opm/models/blackoil/blackoilproblem.hh
  opm/models/blackoil/blackoilproperties.hh
  opm/models/blackoil/blackoilratevector.hh
  opm/models/blackoil/blackoilsolventmodules.hh
Labels: manual:irrelevant

#6289 FlashModel: Some janitoring
  opm/models/flash/flashboundaryratevector.hh
  opm/models/flash/flashintensivequantities.hh
  opm/models/flash/flashlocalresidual.hh
  opm/models/flash/flashmodel.hh
  opm/models/flash/flashprimaryvariables.hh
  opm/models/flash/flashratevector.hh
Labels: manual:irrelevant

#6291 NcpModel: Some janitoring
  opm/models/ncp/ncpboundaryratevector.hh
  opm/models/ncp/ncpextensivequantities.hh
  opm/models/ncp/ncpindices.hh
  opm/models/ncp/ncpintensivequantities.hh
  opm/models/ncp/ncplocalresidual.hh
  opm/models/ncp/ncpmodel.hh
  opm/models/ncp/ncpnewtonmethod.hh
  opm/models/ncp/ncpprimaryvariables.hh
  opm/models/ncp/ncpproperties.hh
  opm/models/ncp/ncpratevector.hh
Labels: manual:irrelevant

#6292 models/Utils: Some janitoring
  opm/models/nonlinear/newtonmethod.hh
  opm/models/parallel/gridcommhandles.hh
  opm/models/parallel/mpibuffer.hh
  opm/models/parallel/tasklets.cpp
  opm/models/parallel/tasklets.hpp
  opm/models/parallel/threadedentityiterator.hh
Labels: manual:irrelevant

#6293 Allow For Regex Metacharacters in Case Name During File Removal
  opm/simulators/utils/readDeck.cpp
Labels: manual:bugfix

#6298 Ptflash model: some janitoring
  opm/models/ptflash/flashindices.hh
  opm/models/ptflash/flashintensivequantities.hh
  opm/models/ptflash/flashlocalresidual.hh
  opm/models/ptflash/flashmodel.hh
  opm/models/ptflash/flashnewtonmethod.hh
  opm/models/ptflash/flashprimaryvariables.hh
Labels: manual:irrelevant

#6300 Rename the functions globalToLocal, localToGlobal, activeToLocal and …
  opm/simulators/wells/MultisegmentWellEquations.cpp
  opm/simulators/wells/MultisegmentWellSegments.cpp
  opm/simulators/wells/MultisegmentWell_impl.hpp
  opm/simulators/wells/ParallelWellInfo.cpp
  opm/simulators/wells/ParallelWellInfo.hpp
  opm/simulators/wells/WellState.cpp
Labels: manual:irrelevant

#6301 Pvs model: Some janitoring
  opm/models/pvs/pvsboundaryratevector.hh
  opm/models/pvs/pvsextensivequantities.hh
  opm/models/pvs/pvsindices.hh
  opm/models/pvs/pvsintensivequantities.hh
  opm/models/pvs/pvslocalresidual.hh
  opm/models/pvs/pvsmodel.hh
  opm/models/pvs/pvsnewtonmethod.hh
  opm/models/pvs/pvsprimaryvariables.hh
  opm/models/pvs/pvsproperties.hh
  opm/models/pvs/pvsratevector.hh
Labels: manual:irrelevant

#6275 move alq_state to singleWellState
  opm/simulators/wells/ALQState.cpp
  opm/simulators/wells/ALQState.hpp
  opm/simulators/wells/BlackoilWellModelGasLift.cpp
  opm/simulators/wells/BlackoilWellModelGeneric.cpp
  opm/simulators/wells/GasLiftCommon.cpp
  opm/simulators/wells/GasLiftCommon.hpp
  opm/simulators/wells/GasLiftGroupInfo.cpp
  opm/simulators/wells/GasLiftSingleWellGeneric.cpp
  opm/simulators/wells/GasLiftSingleWell_impl.hpp
  opm/simulators/wells/GasLiftStage2.cpp
  opm/simulators/wells/SingleWellState.cpp
  opm/simulators/wells/SingleWellState.hpp
  opm/simulators/wells/WellGroupHelpers.cpp
  opm/simulators/wells/WellGroupHelpers.hpp
  opm/simulators/wells/WellInterfaceGeneric.cpp
  opm/simulators/wells/WellInterface_impl.hpp
  opm/simulators/wells/WellState.cpp
  opm/simulators/wells/WellState.hpp
  tests/test_ALQState.cpp
Labels: manual:irrelevant
