Repository OPM/opm-simulators, pull requests merged in 2025-08, with the labels that each got.

#6379 MPI support for the new GPU aware ISTL Solver
  CMakeLists_files.cmake
  opm/simulators/linalg/FlowLinearSolverParameters.cpp
  opm/simulators/linalg/FlowLinearSolverParameters.hpp
  opm/simulators/linalg/gpuistl/FlexibleSolver_gpu_instantiate.cpp
  opm/simulators/linalg/gpuistl/GpuAwareMPISender.hpp
  opm/simulators/linalg/gpuistl/GpuObliviousMPISender.hpp
  opm/simulators/linalg/gpuistl/GpuOwnerOverlapCopy.hpp
  opm/simulators/linalg/gpuistl/GpuSender.hpp
  opm/simulators/linalg/gpuistl/GpuSparseMatrix.hpp
  opm/simulators/linalg/gpuistl/PreconditionerFactory_gpu_instantiate.cpp
  opm/simulators/linalg/gpuistl/SolverAdapter.hpp
  opm/simulators/linalg/gpuistl/detail/FlexibleSolverWrapper.cpp
  tests/gpuistl/test_GpuOwnerOverlapCopy.cpp
Labels: manual:enhancement

#6390 enable tuning for network_01_wtest
  regressionTests.cmake
Labels: manual:irrelevant

#6392 Add End-of-Episode Predicate to Flow Problem Classes
  opm/simulators/flow/FlowProblem.hpp
  opm/simulators/flow/FlowProblemBlackoil.hpp
  opm/simulators/flow/FlowProblemComp.hpp
Labels: manual:irrelevant

#6393 Add in satellite production in reduction rates
  opm/simulators/wells/FractionCalculator.cpp
  opm/simulators/wells/WellGroupHelpers.cpp
Labels: manual:irrelevant

#6394 Update handling of depth=contact to use topmost fluid
  opm/simulators/flow/equil/EquilibrationHelpers_impl.hpp
Labels: manual:irrelevant

#6051 Check status from wellstate not the well object from Schedule
  opm/simulators/wells/BlackoilWellModelGeneric.cpp
  opm/simulators/wells/GuideRateHandler.cpp
  opm/simulators/wells/MultisegmentWell_impl.hpp
  opm/simulators/wells/StandardWell_impl.hpp
  opm/simulators/wells/WellGroupHelpers.cpp
  opm/simulators/wells/WellInterface_impl.hpp
Labels: manual:bugfix

#6277 [doc] Updated man page to reflect changes of flow help message.
  doc/man1/flow.1
Labels: manual:irrelevant

#6398 Added --expt-relaxed-constexpr to test_gpuBlackOilFluidSystem
  CMakeLists_files.cmake
Labels: manual:irrelevant

#6421 remove unused lambda capture
  opm/simulators/wells/BlackoilWellModel.hpp
  opm/simulators/wells/BlackoilWellModelGeneric.cpp
  opm/simulators/wells/BlackoilWellModelGeneric.hpp
Labels: manual:irrelevant

#6425 fixed: argument order differ in prototype and implementation
  opm/simulators/flow/BlackoilModel.hpp
  opm/simulators/flow/LogOutputHelper.hpp
Labels: manual:irrelevant

#6426 Janitoring: quell some SCA warnings
  examples/art2dgf.cpp
  opm/models/blackoil/blackoilpolymerparams.cpp
  opm/simulators/flow/SimulatorSerializer.cpp
  opm/simulators/wells/BlackoilWellModelGasLift_impl.hpp
  opm/simulators/wells/GasLiftCommon.cpp
  opm/simulators/wells/GasLiftStage2.cpp
  opm/simulators/wells/MultisegmentWellEval.cpp
  opm/simulators/wells/VFPHelpers.cpp
  opm/simulators/wells/WellBhpThpCalculator.cpp
Labels: manual:irrelevant

#6430 Add CUDA version checks for GpuSparseMatrixGeneric
  opm/simulators/linalg/gpuistl/GpuSparseMatrixGeneric.cpp
Labels: manual:irrelevant

#6423 Add support for GPU input types with AMGX
  CMakeLists.txt
  CMakeLists_files.cmake
  opm/simulators/linalg/AmgxPreconditioner.hpp
  opm/simulators/linalg/StandardPreconditioners_gpu_serial.hpp
  opm/simulators/linalg/gpuistl/AmgxInterface.hpp
  opm/simulators/linalg/gpuistl/detail/gpu_type_detection.hpp
  tests/AmgxPreconditionerTestHelper.hpp
  tests/gpuistl/test_AmgxInterface.cpp
  tests/test_AmgxPreconditioner.cpp
Labels: manual:enhancement

#6386 Faster pvt
  opm/models/blackoil/blackoilintensivequantities.hh
Labels: manual:enhancement

#6428 Serialise Satellite Injection Rates in Parallel
  opm/simulators/flow/FlowGenericVanguard.cpp
  opm/simulators/utils/ParallelSerialization.cpp
  tests/test_ParallelSerialization.cpp
Labels: manual:irrelevant

#6431 Test WEFAC with PyAction in parallel
  pyactionActionXComparisons.cmake
Labels: manual:irrelevant

#6433 initialize variables
  opm/simulators/wells/GasLiftSingleWellGeneric.cpp
Labels: manual:irrelevant
