Repository OPM/opm-simulators, pull requests merged in 2025-09, with the labels that each got.

#6338 Reduce osscilations between stop and open
  flowexperimental/flowexp.hpp
  opm/simulators/flow/BlackoilModelParameters.cpp
  opm/simulators/flow/BlackoilModelParameters.hpp
  opm/simulators/wells/MultisegmentWell_impl.hpp
  opm/simulators/wells/StandardWell_impl.hpp
Labels: manual:enhancement

#6358 For oscillation detection we only count gr switching after nupcol.
  opm/simulators/wells/BlackoilWellModelConstraints.cpp
  opm/simulators/wells/BlackoilWellModelConstraints.hpp
  opm/simulators/wells/BlackoilWellModelGeneric.cpp
  opm/simulators/wells/BlackoilWellModelGeneric.hpp
  opm/simulators/wells/BlackoilWellModel_impl.hpp
Labels: manual:enhancement

#6367 Compiletime threephaseswitch
  flow/flow_blackoil.cpp
  opm/models/blackoil/blackoilintensivequantities.hh
  opm/simulators/flow/FIBlackoilModel.hpp
  opm/simulators/flow/FlowBaseProblemProperties.hpp
  opm/simulators/flow/FlowProblem.hpp
Labels: manual:enhancement

#6419 Make cpr weight calculation thread parallel
  opm/simulators/linalg/ISTLSolver.hpp
  opm/simulators/linalg/getQuasiImpesWeights.hpp
Labels: manual:enhancement

#6440 Reservoir coupling: Allow slaves and master to activate at different times
  opm/simulators/flow/ReservoirCoupling.cpp
  opm/simulators/flow/ReservoirCoupling.hpp
  opm/simulators/flow/ReservoirCouplingMaster.cpp
  opm/simulators/flow/ReservoirCouplingMaster.hpp
  opm/simulators/flow/ReservoirCouplingSlave.cpp
  opm/simulators/flow/ReservoirCouplingSlave.hpp
  opm/simulators/flow/ReservoirCouplingSpawnSlaves.cpp
  opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp
  opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp
  opm/simulators/wells/GuideRateHandler.cpp
  tests/rescoup/test_chopstep.cpp
Labels: manual:irrelevant

#6449 Fix RFT State Collection for Distributed Wells
  CMakeLists_files.cmake
  opm/simulators/flow/GenericOutputBlackoilModule.cpp
  opm/simulators/flow/GenericOutputBlackoilModule.hpp
  opm/simulators/flow/OutputBlackoilModule.hpp
  opm/simulators/flow/OutputCompositionalModule.hpp
  opm/simulators/flow/RFTContainer.cpp
  opm/simulators/flow/RFTContainer.hpp
  opm/simulators/wells/BlackoilWellModelGeneric.hpp
  parallelUnitTests.cmake
  tests/test_rftcontainer.cpp
Labels: manual:bugfix

#6460 removing instantiation for two Indices setup with non-zero PVOffset
  opm/simulators/utils/InstantiationIndicesMacros.hpp
Labels: manual:irrelevant

#6461 Fix python setup.py warnings
  python/docker/scripts/generate-pypi-package.sh
  python/pyproject.toml
  python/setup.py.in
Labels: manual:irrelevant

#6465 python packaging: enable LTO
  python/docker/scripts/build-boost.sh
  python/docker/scripts/build-dune.sh
  python/docker/scripts/generate-pypi-package.sh
Labels: manual:irrelevant

#6468 Dont go back to classical approach during un-converged operability check
  opm/simulators/wells/WellInterface_impl.hpp
Labels: manual:irrelevant

#6469 some cleaning up in blackoilprimaryvariables
  opm/models/blackoil/blackoilprimaryvariables.hh
Labels: manual:irrelevant

#6474 Added include of cstdint
  opm/simulators/wells/WellHelpers.hpp
Labels: manual:irrelevant

#6473 incorporating the item 22 of WSEGAICD
  opm/simulators/wells/MultisegmentWellSegments.cpp
Labels: manual:new-feature

#6050 Support opening of following-on well
  opm/simulators/wells/BlackoilWellModel.hpp
  opm/simulators/wells/BlackoilWellModel_impl.hpp
  opm/simulators/wells/SingleWellState.cpp
  opm/simulators/wells/SingleWellState.hpp
  opm/simulators/wells/WellState.cpp
  opm/simulators/wells/WellTest.cpp
  regressionTests.cmake
Labels: manual:enhancement

#6463 Dont include temporary stopped wells among the wells considered for group control
  opm/simulators/wells/BlackoilWellModelGeneric.cpp
  opm/simulators/wells/BlackoilWellModel_impl.hpp
  opm/simulators/wells/WellInterfaceGeneric.hpp
  opm/simulators/wells/WellState.cpp
  opm/simulators/wells/WellState.hpp
Labels: manual:irrelevant

#6478 python packaging: update to use python_simulator_modules target
  python/docker/run-docker-build.sh
Labels: manual:irrelevant

#6472 Fix MPI parallel ISTLSolverGPUISTL and register parallel GPU preconditioners
  CMakeLists_files.cmake
  opm/simulators/linalg/StandardPreconditioners_gpu_mpi.hpp
  opm/simulators/linalg/StandardPreconditioners_gpu_serial.hpp
  opm/simulators/linalg/gpuistl/ISTLSolverGPUISTL.hpp
  opm/simulators/linalg/gpuistl/detail/FlexibleSolverWrapper.cpp
  opm/simulators/linalg/gpuistl/detail/FlexibleSolverWrapper.hpp
  opm/simulators/linalg/gpuistl/detail/gpu_preconditioner_utils.hpp
Labels: manual:enhancement

#6308 CPR-AMG fully on the GPU with GpuIstl
  CMakeLists.txt
  CMakeLists_files.cmake
  opm/simulators/linalg/FlowLinearSolverParameters.cpp
  opm/simulators/linalg/OwningTwoLevelPreconditioner.hpp
  opm/simulators/linalg/PreconditionerFactoryGPUIncludeWrapper.hpp
  opm/simulators/linalg/StandardPreconditioners_gpu_serial.hpp
  opm/simulators/linalg/getQuasiImpesWeights.hpp
  opm/simulators/linalg/gpuistl/GpuPressureTransferPolicy.hpp
  opm/simulators/linalg/gpuistl/GpuVector.cpp
  opm/simulators/linalg/gpuistl/GpuVector.hpp
  opm/simulators/linalg/gpuistl/ISTLSolverGPUISTL.hpp
  opm/simulators/linalg/gpuistl/detail/cpr_amg_operations.cu
  opm/simulators/linalg/gpuistl/detail/cpr_amg_operations.hpp
  opm/simulators/linalg/gpuistl/detail/deviceBlockOperations.hpp
  opm/simulators/linalg/gpuistl/hypreinterface/HypreCpuTransfers.hpp
  opm/simulators/linalg/gpuistl/hypreinterface/HypreSetup.hpp
  opm/simulators/linalg/matrixblock.hh
  opm/simulators/linalg/setupPropertyTree.cpp
  opm/simulators/linalg/twolevelmethodcpr.hh
  tests/gpuistl/test_GpuPressureTransferPolicy.cpp
  tests/gpuistl/test_deviceBlockOperations.cu
Labels: manual:new-feature

#6487 Biofilm and Calcite set to volume fraction instead of concentration
  opm/models/blackoil/blackoilbioeffectsmodules.hh
  opm/models/blackoil/blackoilintensivequantities.hh
  opm/models/blackoil/blackoilnewtonmethod.hpp
  opm/models/blackoil/blackoilonephaseindices.hh
  opm/models/blackoil/blackoilprimaryvariables.hh
  opm/models/blackoil/blackoiltwophaseindices.hh
  opm/models/blackoil/blackoilvariableandequationindices.hh
  opm/models/io/vtkblackoilbioeffectsmodule.hpp
  opm/models/io/vtkblackoilbioeffectsparams.cpp
  opm/models/io/vtkblackoilbioeffectsparams.hpp
  opm/simulators/flow/BioeffectsContainer.cpp
  opm/simulators/flow/BioeffectsContainer.hpp
  opm/simulators/flow/BlackoilModel.hpp
  opm/simulators/flow/FlowGenericProblem.hpp
  opm/simulators/flow/FlowGenericProblem_impl.hpp
  opm/simulators/flow/FlowProblemBlackoil.hpp
  opm/simulators/flow/OutputBlackoilModule.hpp
  opm/simulators/flow/SolutionContainers.cpp
  opm/simulators/flow/SolutionContainers.hpp
  opm/simulators/utils/ComponentName.cpp
Labels: manual:irrelevant

#6495 Avoid ending up as GRUP when oscillating
  opm/simulators/wells/WellInterface_impl.hpp
Labels: manual:irrelevant

#6470 Update well/group controls before network updates
  opm/simulators/wells/BlackoilWellModel_impl.hpp
Labels: manual:irrelevant

#6496 Fix GPU backend specification for Hypre
  opm/simulators/linalg/HyprePreconditioner.hpp
Labels: manual:irrelevant

#6480 Add check to disallow RESV/VREP-control for groups having satellite sub-groups
  opm/simulators/utils/readDeck.cpp
Labels: manual:enhancement

#6483 Pre-commit framework
  .pre-commit-config.yaml
  README.md
Labels: manual:irrelevant

#6503 Use new lineariser for simulators with EnableBrine
  flow/flow_brine.cpp
  flow/flow_brine_energy.cpp
  flow/flow_brine_precsalt_vapwat.cpp
  flow/flow_brine_saltprecipitation.cpp
  flow/flow_gaswater_brine.cpp
  flow/flow_gaswater_saltprec_energy.cpp
  flow/flow_gaswater_saltprec_vapwat.cpp
  flow/flow_oilwater_brine.cpp
  opm/models/blackoil/blackoilbrinemodules.hh
  opm/models/blackoil/blackoillocalresidual.hh
  opm/models/blackoil/blackoillocalresidualtpfa.hh
Labels: manual:irrelevant
